# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'final.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys, design.resources.img

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1383, 758)
        font = QtGui.QFont()
        font.setPointSize(7)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setStyleSheet("background: #2F2F2F;\n"
"border-radius: 23px;")
        self.widget_2.setObjectName("widget_2")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setGeometry(QtCore.QRect(22, 64, 55, 55))
        self.widget_3.setStyleSheet("image: url(:/img/Images/00_Logo.png);\n"
"background-color:rgba(255,255,255,0);")
        self.widget_3.setObjectName("widget_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_2.setGeometry(QtCore.QRect(162, 628, 200, 113))
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    \n"
"    border-image: url(:/img/Images/06_img2.jpeg);\n"
"     border-radius:15px;\n"
"}\n"
"QPushButton:hover{\n"
"    border-image: url(:/img/Images/06_img2.jpeg);\n"
"     border-radius:15px;\n"
"}\n"
"QPushButton:pressed{\n"
"    border-image: url(:/img/Images/06_img2.jpeg);\n"
"     border-radius:15px;\n"
"}")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_3.setGeometry(QtCore.QRect(162, 628, 200, 113))
        self.pushButton_3.setStyleSheet("\n"
"QPushButton{\n"
"    background-color:rgba(255,255,255,100);\n"
"    border-radius:15px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgba(255,255,255,0);\n"
"    border-radius:15px;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgba(255,255,255,0);\n"
"    border-radius:15px;\n"
"}")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_8 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_8.setGeometry(QtCore.QRect(390, 627, 200, 113))
        self.pushButton_8.setStyleSheet("\n"
"QPushButton{\n"
"    \n"
"    border-image: url(:/img/Images/06_img4.jpeg);\n"
"     border-radius:15px;\n"
"}\n"
"QPushButton:hover{\n"
"    border-image: url(:/img/Images/06_img4.jpeg);\n"
" \n"
"}\n"
"QPushButton:pressed{\n"
"    border-image: url(:/img/Images/06_img4.jpeg);\n"
"     \n"
"}\n"
"")
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_17 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_17.setGeometry(QtCore.QRect(390, 627, 200, 113))
        self.pushButton_17.setStyleSheet("\n"
"QPushButton{\n"
"    background-color:rgba(255,255,255,100);\n"
"    border-radius:15px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgba(255,255,255,0);\n"
"    \n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgba(255,255,255,0);\n"
"    \n"
"}")
        self.pushButton_17.setText("")
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_18.setGeometry(QtCore.QRect(619, 628, 200, 113))
        self.pushButton_18.setStyleSheet("\n"
"QPushButton{\n"
"    background-color:rgba(255,255,255,100);\n"
"    border-radius:15px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgba(255,255,255,0);\n"
"    \n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgba(255,255,255,0);\n"
"    \n"
"}")
        self.pushButton_18.setText("")
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_19.setGeometry(QtCore.QRect(619, 628, 200, 113))
        self.pushButton_19.setStyleSheet("QPushButton{\n"
"    \n"
"    border-image: url(:/img/Images/06_img3.jpeg);\n"
"     border-radius:15px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    border-image: url(:/img/Images/06_img3.jpeg);\n"
"     \n"
"}\n"
"QPushButton:pressed{\n"
"    border-image: url(:/img/Images/06_img3.jpeg);\n"
"     \n"
"}\n"
"")
        self.pushButton_19.setText("")
        self.pushButton_19.setObjectName("pushButton_19")
        self.timeEdit = QtWidgets.QTimeEdit(self.widget_2)
        self.timeEdit.setGeometry(QtCore.QRect(1209, 35, 161, 65))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(37)
        self.timeEdit.setFont(font)
        self.timeEdit.setStyleSheet("background-color:rgba(255,255,255,0);\n"
"border:none;\n"
"color:rgba(255,255,255,255);")
        self.timeEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.timeEdit.setTime(QtCore.QTime(10, 36, 0))
        self.timeEdit.setObjectName("timeEdit")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(1247, 95, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:rgba(255,255,255,0);\n"
"border:none;\n"
"color:rgba(255,255,255,255);\n"
"\n"
"")
        self.label.setObjectName("label")
        self.widget_5 = QtWidgets.QWidget(self.widget_2)
        self.widget_5.setGeometry(QtCore.QRect(205, 202, 639, 359))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.widget_5.setFont(font)
        self.widget_5.setStyleSheet("image: url(:/img/Images/06_img1.png);\n"
"background-color:rgba(255,255,255,0);\n"
"border:none;\n"
"")
        self.widget_5.setObjectName("widget_5")
        self.pushButton_23 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_23.setGeometry(QtCore.QRect(857, 665, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setStyleSheet("\n"
"QPushButton {\n"
"   \n"
"    background-color:rgba(194, 194, 194, 0.25);\n"
"    border-radius:8px;\n"
"  }\n"
"QPushButton:hover {\n"
"    background-color:rgba(194, 194, 194, 0.25);\n"
" border: 2px solid #000000;\n"
"    /*border-radius:5px;*/\n"
"\n"
"    }\n"
"QPushButton:pressed {\n"
"  background-color:rgba(194, 194, 194, 0.25);\n"
" border: 2px solid #000000;\n"
"   /*border-radius:5px;*/\n"
"    }\n"
"\n"
"")
        self.pushButton_23.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/Images/07_next_img.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/img/Images/07_next_img.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_23.setIcon(icon)
        self.pushButton_23.setIconSize(QtCore.QSize(11, 18))
        self.pushButton_23.setObjectName("pushButton_23")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(140, 591, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:#737373;\n"
"border:none;\n"
"background-color:none;\n"
"")
        self.label_2.setObjectName("label_2")
        self.widget_6 = QtWidgets.QWidget(self.widget_2)
        self.widget_6.setGeometry(QtCore.QRect(982, 645, 361, 77))
        self.widget_6.setStyleSheet("background-color:#737373;\n"
"border-radius:10px;")
        self.widget_6.setObjectName("widget_6")
        self.textEdit_4 = QtWidgets.QTextEdit(self.widget_6)
        self.textEdit_4.setGeometry(QtCore.QRect(215, 5, 141, 71))
        font = QtGui.QFont()
        font.setFamily("Ebrima")
        self.textEdit_4.setFont(font)
        self.textEdit_4.setStyleSheet("background-color:rgba(255,255,255,0);\n"
"border:20px\n"
"")
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_3 = QtWidgets.QTextEdit(self.widget_6)
        self.textEdit_3.setGeometry(QtCore.QRect(22, 5, 161, 75))
        font = QtGui.QFont()
        font.setFamily("Ebrima")
        font.setPointSize(7)
        self.textEdit_3.setFont(font)
        self.textEdit_3.setStyleSheet("background-color:rgba(255,255,255,0);\n"
"border:15px\n"
"")
        self.textEdit_3.setObjectName("textEdit_3")
        self.pushButton_20 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_20.setGeometry(QtCore.QRect(870, 365, 55, 55))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(19)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setStyleSheet("\n"
"QPushButton{\n"
"    background-color:rgba(47, 47, 47, 1);\n"
"    color:rgba(255,255,255,255);\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgba(47, 47, 47, 1);\n"
"    color:rgba(0,132,0,255);\n"
"    \n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgba(47, 47, 47, 1);\n"
"    color:rgba(0,132,0,255);\n"
"    \n"
"}\n"
"")
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_21.setGeometry(QtCore.QRect(116, 365, 55, 55))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(17)
        self.pushButton_21.setFont(font)
        self.pushButton_21.setStyleSheet("QPushButton{\n"
"    background-color:rgba(47, 47, 47, 1);\n"
"    color:rgba(255,255,255,255);\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgba(47, 47, 47, 1);\n"
"    color:rgba(0,132,0,255);\n"
"    \n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgba(47, 47, 47, 1);\n"
"    color:rgba(0,132,0,255);\n"
"    \n"
"}\n"
"")
        self.pushButton_21.setObjectName("pushButton_21")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(974, 410, 374, 33))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #FFFFFF;\n"
"background-color: #272121;\n"
"border-left: 7px solid #3225CC;")
        self.label_3.setObjectName("label_3")
        self.widget_7 = QtWidgets.QWidget(self.widget_2)
        self.widget_7.setGeometry(QtCore.QRect(97, 49, 2, 658))
        self.widget_7.setStyleSheet("background-color: #2F2F2F;")
        self.widget_7.setObjectName("widget_7")
        self.widget_8 = QtWidgets.QWidget(self.widget_7)
        self.widget_8.setGeometry(QtCore.QRect(0, 444, 2, 54))
        self.widget_8.setStyleSheet("background-color: #0083FF;")
        self.widget_8.setObjectName("widget_8")
        self.widget_9 = QtWidgets.QWidget(self.widget_7)
        self.widget_9.setGeometry(QtCore.QRect(0, 160, 2, 54))
        self.widget_9.setStyleSheet("background-color: #0083FF;")
        self.widget_9.setObjectName("widget_9")
        self.widget_10 = QtWidgets.QWidget(self.widget_7)
        self.widget_10.setGeometry(QtCore.QRect(0, 302, 2, 54))
        self.widget_10.setStyleSheet("background-color: #0083FF;")
        self.widget_10.setObjectName("widget_10")
        self.widget_11 = QtWidgets.QWidget(self.widget_7)
        self.widget_11.setGeometry(QtCore.QRect(0, 373, 2, 54))
        self.widget_11.setStyleSheet("background-color: #0083FF;")
        self.widget_11.setObjectName("widget_11")
        self.widget_12 = QtWidgets.QWidget(self.widget_7)
        self.widget_12.setGeometry(QtCore.QRect(0, 232, 2, 54))
        self.widget_12.setStyleSheet("background-color: #0083FF;")
        self.widget_12.setObjectName("widget_12")
        self.pushButton_22 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_22.setGeometry(QtCore.QRect(40, 296, 21, 21))
        self.pushButton_22.setStyleSheet("QPushButton {\n"
"    qproperty-icon: url(\" \"); /* empty image */\n"
"    qproperty-iconSize: 16px 16px; /* space for the background image */\n"
"    border-image: url(:/img/Images/01_adjust_0.png);\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    background-color: rgba(255,255,255,0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"       border-image: url(:/img/Images/01_adjust_1.png);\n"
"    background-repeat: no-repeat;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"      border-image: url(:/img/Images/01_adjust_1.png);\n"
"    background-repeat: no-repeat;\n"
"}")
        self.pushButton_22.setText("")
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_24 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_24.setGeometry(QtCore.QRect(38, 435, 28, 29))
        self.pushButton_24.setStyleSheet("QPushButton {\n"
"    qproperty-icon: url(\" \"); /* empty image */\n"
"    qproperty-iconSize: 16px 16px; /* space for the background image */\n"
"    border-image: url(:/img/Images/01_location_0.png);\n"
"    background-repeat: no-repeat;\n"
"    background-color:rgba(255,255,255,0);\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     border-image: url(:/img/Images/01_location_1.png);\n"
"    background-repeat: no-repeat;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-image: url(:/img/Images/01_location_1.png);\n"
"    background-repeat: no-repeat;\n"
"}")
        self.pushButton_24.setText("")
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_25 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_25.setGeometry(QtCore.QRect(40, 366, 23, 23))
        self.pushButton_25.setStyleSheet("QPushButton {\n"
"    qproperty-icon: url(\" \"); /* empty image */\n"
"    qproperty-iconSize: 16px 16px; /* space for the background image */\n"
"    border-image: url(:/img/Images/01_spiral_0.png);\n"
"    background-color:rgba(255,255,255,0);\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-image: url(:/img/Images/01_spiral_1.png);\n"
"    background-repeat: no-repeat;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-image: url(:/img/Images/01_spiral_1.png);\n"
"    background-repeat: no-repeat;\n"
"}")
        self.pushButton_25.setText("")
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_26 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_26.setGeometry(QtCore.QRect(41, 507, 26, 26))
        self.pushButton_26.setStyleSheet("QPushButton {\n"
"    qproperty-icon: url(\" \"); \n"
"    qproperty-iconSize: 16px 16px; \n"
"    border-image: url(:/img/Images/01_globe_0.png);\n"
"    background-color:rgba(255,255,255,0);\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"       border-image: url(:/img/Images/01_globe_1.png);\n"
"    background-repeat: no-repeat;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"       border-image: url(:/img/Images/01_globe_1.png);\n"
"    background-repeat: no-repeat;\n"
"}")
        self.pushButton_26.setText("")
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        self.pushButton.setGeometry(QtCore.QRect(36, 225, 25, 23))
        self.pushButton.setStyleSheet("\n"
"QPushButton {\n"
"    qproperty-icon: url(\" \"); /* empty image */\n"
"    qproperty-iconSize: 16px 16px; /* space for the background image */\n"
"    border-image: url(:/img/Images/01_revert_0.png);\n"
"    background-repeat: no-repeat;\n"
"    background-color:rgba(255,255,255,0);\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"       border-image: url(:/img/Images/01_revert_1.png);\n"
"    background-repeat: no-repeat;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"       border-image: url(:/img/Images/01_revert_1.png);\n"
"    background-repeat: no-repeat;\n"
"}")
        self.pushButton.setText("")
        self.pushButton.setIconSize(QtCore.QSize(16, 16))
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_28 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_28.setGeometry(QtCore.QRect(22, 638, 61, 61))
        self.pushButton_28.setStyleSheet("border: none;\n"
"background-color:rgba(255,255,255,0);\n"
"")
        self.pushButton_28.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/Images/03_github.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/img/Images/03_github.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_28.setIcon(icon1)
        self.pushButton_28.setIconSize(QtCore.QSize(58, 58))
        self.pushButton_28.setObjectName("pushButton_28")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_2.setGeometry(QtCore.QRect(970, 485, 381, 121))
        self.groupBox_2.setStyleSheet("background-color:rgba(255,255,255,0);\n"
"border: none;")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(55, 74, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: #FFFFFF;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(258, -3, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: #FFFFFF;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(258, 36, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: #FFFFFF;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(256, 67, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: #FFFFFF;\n"
"border-radius: 20px;\n"
"background-color: rgba(228, 228, 228, 0.04);\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(52, -1, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: #FFFFFF;")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.widget_13 = QtWidgets.QWidget(self.groupBox_2)
        self.widget_13.setGeometry(QtCore.QRect(18, 82, 16, 16))
        self.widget_13.setStyleSheet("border-image: url(:/img/Images/11_blue.png);")
        self.widget_13.setObjectName("widget_13")
        self.widget_14 = QtWidgets.QWidget(self.groupBox_2)
        self.widget_14.setGeometry(QtCore.QRect(18, 45, 16, 16))
        self.widget_14.setStyleSheet("\n"
"border-image: url(:/img/Images/11_green.png);")
        self.widget_14.setObjectName("widget_14")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(57, 37, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: #FFFFFF;")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.widget_15 = QtWidgets.QWidget(self.groupBox_2)
        self.widget_15.setGeometry(QtCore.QRect(30, 130, 16, 21))
        self.widget_15.setStyleSheet("border-image: url(:/others/blue.png);")
        self.widget_15.setObjectName("widget_15")
        self.widget_16 = QtWidgets.QWidget(self.groupBox_2)
        self.widget_16.setGeometry(QtCore.QRect(18, 8, 16, 16))
        self.widget_16.setStyleSheet("border-image: url(:/img/Images/11_red.png);\n"
"")
        self.widget_16.setObjectName("widget_16")
        self.widget_17 = QtWidgets.QWidget(self.groupBox_2)
        self.widget_17.setGeometry(QtCore.QRect(222, 7, 16, 16))
        self.widget_17.setStyleSheet("border-image: url(:/img/Images/11_yellow.png);\n"
"")
        self.widget_17.setObjectName("widget_17")
        self.widget_18 = QtWidgets.QWidget(self.groupBox_2)
        self.widget_18.setGeometry(QtCore.QRect(222, 45, 16, 16))
        self.widget_18.setStyleSheet("border-image: url(:/img/Images/11_orange.png);\n"
"")
        self.widget_18.setObjectName("widget_18")
        self.widget_19 = QtWidgets.QWidget(self.groupBox_2)
        self.widget_19.setGeometry(QtCore.QRect(222, 82, 16, 16))
        self.widget_19.setStyleSheet("border-image: url(:/img/Images/11_purple.png);\n"
"")
        self.widget_19.setObjectName("widget_19")
        self.pushButton_29 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_29.setGeometry(QtCore.QRect(978, 617, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_29.setFont(font)
        self.pushButton_29.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"    color: #737373;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #737373;\n"
"}")
        self.pushButton_29.setObjectName("pushButton_29")
        self.pushButton_30 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_30.setGeometry(QtCore.QRect(1088, 623, 13, 8))
        self.pushButton_30.setStyleSheet("QPushButton {\n"
"    qproperty-icon: url(\" \"); \n"
"    qproperty-iconSize: 16px 16px;\n"
"  \n"
"    border-image: url(:/img/Images/12_dropdown_0.png);\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"background-color: rgba(255,255,255,0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"   border-image: url(:/img/Images/12_dropdown_1.png);\n"
"    background-repeat: no-repeat;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-image: url(:/img/Images/12_dropdown_1.png);\n"
"    background-repeat: no-repeat;\n"
"}")
        self.pushButton_30.setText("")
        self.pushButton_30.setObjectName("pushButton_30")
        self.widget_20 = QtWidgets.QWidget(self.widget_2)
        self.widget_20.setGeometry(QtCore.QRect(956, 50, 48, 48))
        self.widget_20.setStyleSheet("border-image: url(:/img/Images/08_wifi.png);\n"
"background-color: rgba(255,255,255,0);\n"
"border-radius: 16px;")
        self.widget_20.setObjectName("widget_20")
        self.textBrowser = QtWidgets.QTextBrowser(self.widget_2)
        self.textBrowser.setGeometry(QtCore.QRect(1021, 50, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background-color:rgba(255,255,255,0);\n"
"border:none;\n"
"color:#ffffff")
        self.textBrowser.setObjectName("textBrowser")
        self.label_12 = QtWidgets.QLabel(self.widget_2)
        self.label_12.setGeometry(QtCore.QRect(0, 0, 943, 757))
        self.label_12.setStyleSheet("\n"
"background-color:rgba(61, 61, 61, 1);\n"
"border-top-left-radius:23px;\n"
"\n"
"border-bottom-left-radius:23px;")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setGeometry(QtCore.QRect(973, 146, 382, 241))
        self.widget_4.setStyleSheet("background: rgba(228, 228, 228, 0.1);\n"
"border: 1.3px solid rgba(255, 255, 255, 1);\n"
"border-radius:5px;")
        self.widget_4.setObjectName("widget_4")
        self.groupBox = QtWidgets.QGroupBox(self.widget_4)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 381, 241))
        self.groupBox.setStyleSheet("border:none;\n"
"background-color:none;\n"
"color:rgb(255,255,255)")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4.setGeometry(QtCore.QRect(40, 25, 55, 55))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"\n"
"    border-style: outset;\n"
"    background-color: #FF8400;\n"
"    border-radius: 23px;\n"
"   \n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"       /*border: 2px solid #000000;*/\n"
"    background-color: rgb(255,100,0);\n"
"    }\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"       background-color: #FF8400;\n"
"    }\n"
"")
        self.pushButton_4.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/Images/09_draw.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/img/Images/09_draw.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_4.setIcon(icon2)
        self.pushButton_4.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_9.setGeometry(QtCore.QRect(40, 130, 55, 55))
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"   \n"
"    border-style: outset;\n"
"    background-color: #548A56;\n"
"    border-radius:23px;\n"
"  \n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"     \n"
"     background-color: rgb(60,130,80);\n"
"    }\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"       background-color: #548A56;\n"
"    }\n"
"")
        self.pushButton_9.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/Images/09_zoomin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/img/Images/09_zoomin.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_9.setIcon(icon3)
        self.pushButton_9.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_9.setShortcut("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_10.setGeometry(QtCore.QRect(164, 25, 55, 55))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setStyleSheet("QPushButton {\n"
"   \n"
"    border-style: outset;\n"
"    background-color: #0083FF;\n"
"    border-radius: 23px;\n"
"    \n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"     \n"
"     background-color: rgb(45,90,250);\n"
"    }\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"       background-color: #0083FF;\n"
"    }\n"
"")
        self.pushButton_10.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img/Images/09_point.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":/img/Images/09_point.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_10.setIcon(icon4)
        self.pushButton_10.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_10.setShortcut("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_13.setGeometry(QtCore.QRect(285, 25, 55, 55))
        self.pushButton_13.setStyleSheet("QPushButton {\n"
"    border-style: outset;\n"
"    background-color: #B944C4;\n"
"    border-radius: 23px;\n"
"   \n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"     background-color: rgb(160,50,180);\n"
"     \n"
"     \n"
"    }\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"       background-color: #B944C4;\n"
"    }\n"
"")
        self.pushButton_13.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/img/Images/09_undo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap(":/img/Images/09_undo.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_13.setIcon(icon5)
        self.pushButton_13.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_13.setShortcut("")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_11.setGeometry(QtCore.QRect(164, 130, 55, 55))
        self.pushButton_11.setStyleSheet("QPushButton {\n"
"    \n"
"    border-style: outset;\n"
"    background-color: #1DB158;\n"
"    border-radius: 23px;\n"
"    \n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"     background-color: rgb(30,145,80);\n"
"     \n"
"    }\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"       background-color: #1DB158;\n"
"    }\n"
"")
        self.pushButton_11.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/img/Images/09_zoomout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(":/img/Images/09_zoomout.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_11.setIcon(icon6)
        self.pushButton_11.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_11.setShortcut("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_12.setGeometry(QtCore.QRect(285, 130, 55, 55))
        self.pushButton_12.setStyleSheet("QPushButton {\n"
"    border-style: outset;\n"
"    background-color: #48CAF3;\n"
"    border-radius: 23px;\n"
"  \n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"     background-color: rgb(0,185,255);\n"
"     \n"
"    }\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"       background-color: #48CAF3;\n"
"    }\n"
"")
        self.pushButton_12.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/img/Images/09_redo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap(":/img/Images/09_redo.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_12.setIcon(icon7)
        self.pushButton_12.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_12.setShortcut("")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_5.setGeometry(QtCore.QRect(42, 83, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("border:none;\n"
"background-color:none;\n"
"color:rgb(255,255,255)")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_6.setGeometry(QtCore.QRect(167, 83, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("border:none;\n"
"background-color:none;\n"
"color:rgb(255,255,255)")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_16.setGeometry(QtCore.QRect(287, 83, 51, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setStyleSheet("border:none;\n"
"background-color:none;")
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_15 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_15.setGeometry(QtCore.QRect(148, 187, 91, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setStyleSheet("border:none;\n"
"background-color:none;\n"
"color:rgb(255,255,255)")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_14.setGeometry(QtCore.QRect(287, 187, 51, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setStyleSheet("border:none;\n"
"background-color:none;")
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_7.setGeometry(QtCore.QRect(32, 187, 71, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("border:none;\n"
"background-color:none;\n"
"color:rgb(255,255,255)\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_27 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_27.setGeometry(QtCore.QRect(180, 215, 21, 21))
        self.pushButton_27.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/img/Images/10_uparrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap(":/img/Images/10_uparrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_27.setIcon(icon8)
        self.pushButton_27.setObjectName("pushButton_27")
        self.label_10 = QtWidgets.QLabel(self.widget_2)
        self.label_10.setGeometry(QtCore.QRect(714, 103, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: #737373;\n"
"background-color: rgba(255,255,255,0);")
        self.label_10.setObjectName("label_10")
        self.frame_7 = QtWidgets.QFrame(self.widget_2)
        self.frame_7.setGeometry(QtCore.QRect(680, 109, 28, 28))
        self.frame_7.setStyleSheet("image: url(:/img/Images/05_tracker.png);\n"
"background-color: rgba(255,255,255,0);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_11 = QtWidgets.QLabel(self.widget_2)
        self.label_11.setGeometry(QtCore.QRect(673, 74, 185, 29))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: #FFFFFF;\n"
"background-color: rgba(255,255,255,0);")
        self.label_11.setObjectName("label_11")
        self.toolButton = QtWidgets.QToolButton(self.widget_2)
        self.toolButton.setGeometry(QtCore.QRect(865, 66, 28, 28))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.toolButton.setFont(font)
        self.toolButton.setStyleSheet("background-color: rgba(255,255,255,0);\n"
"border: none;\n"
"color: #FFFFFF;")
        self.toolButton.setObjectName("toolButton")
        self.pushButton_32 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_32.setGeometry(QtCore.QRect(137, 73, 18, 27))
        self.pushButton_32.setStyleSheet("QPushButton {\n"
"    \n"
"    qproperty-icon: url(\" \"); \n"
"    qproperty-iconSize: 8px 2px;\n"
"    background-repeat: no-repeat;\n"
"    border-image: url(:/img/Images/04_path_0.png);\n"
"    border: none;\n"
"    background-color: rgba(255,255,255,0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"      \n"
"    border-image: url(:/img/Images/04_path_1.png);\n"
"    background-repeat: no-repeat;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-image: url(:/img/Images/04_path_1.png);\n"
"    background-repeat: no-repeat;\n"
"}")
        self.pushButton_32.setText("")
        self.pushButton_32.setObjectName("pushButton_32")
        self.label_13 = QtWidgets.QLabel(self.widget_2)
        self.label_13.setGeometry(QtCore.QRect(155, 65, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(19)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color:rgba(255,255,255,255);\n"
"Font size: 34.5px;\n"
"background-color:none;\n"
"")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.widget_2)
        self.label_14.setGeometry(QtCore.QRect(155, 100, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(21)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color:rgba(115, 115, 115, 1);\n"
"background-color:none;\n"
"\n"
"")
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.pushButton_33 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_33.setGeometry(QtCore.QRect(127, 80, 9, 14))
        self.pushButton_33.setStyleSheet("QPushButton {\n"
"    border-image: url(:/img/Images/04_path_0.png);\n"
"    qproperty-icon: url(\" \"); \n"
"    qproperty-iconSize: 8px 2px;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    background-color: rgba(255,255,255,0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"      \n"
"    border-image: url(:/img/Images/04_path_1.png);\n"
"    background-repeat: no-repeat;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-image: url(:/img/Images/04_path_1.png);\n"
"    background-repeat: no-repeat;\n"
"}")
        self.pushButton_33.setText("")
        self.pushButton_33.setObjectName("pushButton_33")
        self.pushButton_31 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_31.setGeometry(QtCore.QRect(363, 81, 13, 8))
        self.pushButton_31.setStyleSheet("QPushButton {\n"
"    qproperty-icon: url(\" \"); \n"
"    qproperty-iconSize: 16px 16px;\n"
"   border-image: url(\":/others/drop.png\");\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    background-color: rgba(255,255,255,0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"      border-image: url(\":/others/drop2.png\");\n"
"    background-repeat: no-repeat;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"      border-image: url(\":/others/drop2.png\");\n"
"    background-repeat: no-repeat;\n"
"}")
        self.pushButton_31.setText("")
        self.pushButton_31.setObjectName("pushButton_31")
        self.pushButton_34 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_34.setGeometry(QtCore.QRect(362, 83, 13, 8))
        self.pushButton_34.setStyleSheet("QPushButton {\n"
"    qproperty-icon: url(\" \"); \n"
"    qproperty-iconSize: 16px 16px;\n"
"    border-image: url(:/img/Images/12_dropdown_0.png);\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    background-color: rgba(255,255,255,0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-image: url(:/img/Images/12_dropdown_1.png);\n"
"    background-repeat: no-repeat;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-image: url(:/img/Images/12_dropdown_1.png);\n"
"    background-repeat: no-repeat;\n"
"}")
        self.pushButton_34.setText("")
        self.pushButton_34.setObjectName("pushButton_34")
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_3.setGeometry(QtCore.QRect(12, 14, 78, 20))
        self.groupBox_3.setStyleSheet("border-radius: 9px;\n"
"background-color: rgba(196, 196, 196, 0.08);\n"
"")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_35 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_35.setGeometry(QtCore.QRect(16, 16, 15, 15))
        self.pushButton_35.setStyleSheet("border-radius: 7px;\n"
"background-color: rgba(189, 14, 14, 0.54);\n"
"")
        self.pushButton_35.setText("")
        self.pushButton_35.setObjectName("pushButton_35")
        self.pushButton_36 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_36.setGeometry(QtCore.QRect(43, 16, 15, 15))
        self.pushButton_36.setStyleSheet("border-radius: 7px;\n"
"background-color: rgba(255, 215, 75, 0.6);\n"
"\n"
"")
        self.pushButton_36.setText("")
        self.pushButton_36.setObjectName("pushButton_36")
        self.pushButton_37 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_37.setGeometry(QtCore.QRect(69, 16, 15, 15))
        self.pushButton_37.setStyleSheet("border-radius: 7px;\n"
"background-color: rgba(68, 223, 83, 0.52);\n"
"\n"
"")
        self.pushButton_37.setText("")
        self.pushButton_37.setObjectName("pushButton_37")
        self.label_12.raise_()
        self.pushButton_19.raise_()
        self.widget_3.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_8.raise_()
        self.pushButton_17.raise_()
        self.pushButton_18.raise_()
        self.timeEdit.raise_()
        self.label.raise_()
        self.widget_5.raise_()
        self.pushButton_23.raise_()
        self.label_2.raise_()
        self.widget_6.raise_()
        self.pushButton_20.raise_()
        self.pushButton_21.raise_()
        self.label_3.raise_()
        self.widget_7.raise_()
        self.pushButton_22.raise_()
        self.pushButton_24.raise_()
        self.pushButton_25.raise_()
        self.pushButton_26.raise_()
        self.pushButton.raise_()
        self.pushButton_28.raise_()
        self.groupBox_2.raise_()
        self.pushButton_29.raise_()
        self.pushButton_30.raise_()
        self.widget_20.raise_()
        self.textBrowser.raise_()
        self.widget_4.raise_()
        self.label_10.raise_()
        self.frame_7.raise_()
        self.label_11.raise_()
        self.toolButton.raise_()
        self.pushButton_32.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.pushButton_33.raise_()
        self.pushButton_31.raise_()
        self.pushButton_34.raise_()
        self.groupBox_3.raise_()
        self.pushButton_35.raise_()
        self.pushButton_36.raise_()
        self.pushButton_37.raise_()
        self.verticalLayout.addWidget(self.widget_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.timeEdit.setDisplayFormat(_translate("MainWindow", "hh:mm"))
        self.label.setText(_translate("MainWindow", "  14th August, 2021"))
        self.label_2.setText(_translate("MainWindow", "NEXT IMAGES"))
        self.textEdit_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ebrima\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt; color:#ff0000;\">●</span><span style=\" font-size:7pt; color:#ffffff;\"> 1   52  45  180  125</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt; color:#ffff00;\">●</span><span style=\" font-size:7pt; color:#ffffff;\"> 4   56  28  192  136</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt; color:#ffff00;\">●</span><span style=\" font-size:7pt; color:#ffffff;\"> 8   12  53  172  125</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt; color:#ff0000;\">●</span><span style=\" font-size:7pt; color:#ffffff;\"> 6   25  97  120  158</span></p></body></html>"))
        self.textEdit_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ebrima\'; font-size:7pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt; color:#06dc8e;\">●</span><span style=\" font-size:6pt; color:#005500;\"> </span><span style=\" color:#ffffff;\">1   32  45  170  185</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt; color:#ff0000;\">●</span><span style=\" font-size:6pt; color:#aaaa7f;\"> </span><span style=\" color:#ffffff;\">4   25  89  180  172</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt; color:#05e198;\">●</span><span style=\" font-size:6pt; color:#ffffff;\"> </span><span style=\" color:#ffffff;\">8   28  65  789  147</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt; color:#ff0000;\">●</span><span style=\" font-size:6pt; color:#aaffff;\"> </span><span style=\" color:#ffffff;\">6   25  97  120  158</span></p></body></html>"))
        self.pushButton_20.setText(_translate("MainWindow", "+"))
        self.pushButton_21.setText(_translate("MainWindow", "-"))
        self.label_3.setText(_translate("MainWindow", "   abcdefgh.txt saved successfully!"))
        self.label_7.setText(_translate("MainWindow", "Truck"))
        self.label_6.setText(_translate("MainWindow", "Animal"))
        self.label_5.setText(_translate("MainWindow", "Cycle"))
        self.label_4.setText(_translate("MainWindow", "Traffic Sign"))
        self.label_8.setText(_translate("MainWindow", "Car"))
        self.label_9.setText(_translate("MainWindow", "Person"))
        self.pushButton_29.setText(_translate("MainWindow", "CURRENT LOG"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:15pt;\">Kolkata</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">India</span></p></body></html>"))
        self.pushButton_5.setText(_translate("MainWindow", "Draw"))
        self.pushButton_6.setText(_translate("MainWindow", "Point"))
        self.pushButton_16.setText(_translate("MainWindow", "Undo"))
        self.pushButton_15.setText(_translate("MainWindow", "Zoom Out"))
        self.pushButton_14.setText(_translate("MainWindow", "Redo"))
        self.pushButton_7.setText(_translate("MainWindow", "Zoom In"))
        self.label_10.setText(_translate("MainWindow", "128/12400"))
        self.label_11.setText(_translate("MainWindow", "Object Detection"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.label_13.setText(_translate("MainWindow", "..data/ Images"))
        self.label_14.setText(_translate("MainWindow", "abcdefgh.jpg"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
